### ISSUE TITLE
Py3.5 conda package misses dependencies

### ISSUE THREAD

**Issue by michaelaye** [menpo/conda-mayavi#2]
These 2 conda packages are missing as a dependency in your conda mayavi 4.5 package (thanks so much for that!):

* packaging
* appdirs

**Comment by patricksnape** [comment]
Are they causing an issue during install?

**Comment by michaelaye** [comment]
Not during install, but during import. Things just crash without those packages.

**Comment by patricksnape** [comment]
Hmm - that's weird that I've never seen that before! On what platform?

**Comment by michaelaye** [comment]
Hm, I'm sorry, I cannot reproduce, very weird. Let's shelf this for now. Sorry for the noise.
